# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: repository_lifecycle
description: >-
  A framework for managing data-layer state and app lifecycle events. Repositories are the source of
  truth for data classes and are responsible for data caching and RPC retry logic. This framework
  provides a way to signal repositories when it is safe to make network calls, when it isn't safe,
  and when to clear their data.
version: 0.0.1
homepage: https://github.com/google/repository_lifecycle

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  built_value: ^8.4.1
  flutter: ^3.3.3
  logging: ^1.1.0
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.6
  mockito: ^5.3.2
  quiver: ^3.1.0
  flutter: ^3.3.3
  flutter_test: ^3.3.3